### ISSUE TITLE
validator MUST check expiration time...

### ISSUE THREAD

**Issue by ksriram25** [igorlord/draft-sriram-sidrops-bar-sav#5]
About: "The validator MUST check expiration time of cryptographic objects when they are fetched from the repository before they are added to the local cache. " 

This applies to RAO/ROV also. It probably has been said elsewhere in another RFC. We can delete the whole paragraph, or we should cite the reference if we feel it is important to re-emphasize here.

**Comment by igorlord** [comment]
Can you find an RFC that says so explicitly?  I would be great if this exists.

I can see implementations possibly just copying files into the cache after verifying hashes, and the rest of the verification (cert expirations, CRL, etc) done later when the objects are used.

**Comment by ksriram25** [comment]
I think we can leave the paragraph as is. We can try to find the reference (if there is one) and add it later in the next version.
