### ISSUE TITLE
Question about... consistency of RPKI repositories

### ISSUE THREAD

**Issue by ksriram25** [igorlord/draft-sriram-sidrops-bar-sav#8]
About: "RPKI infrastructure does not guarantee continuous availability or consistency of RPKI repositories."

What do we mean by lack of consistency? Is it carelessness on part of a user, e.g., creating a ROA for less specific and neglecting to create a RAO for more specific? Such things should not be blamed on RPKI repositories.

Usually, we blame IRRs for inconsistencies due to the lack of authorization, quality control, and security. RPKI repositories are intended/designed to be trustworthy.

s/RPKI infrastructure does not guarantee continuous availability or consistency of RPKI repositories. /RPKI infrastructure does not guarantee continuous availability. /

**Comment by igorlord** [comment]
RFC9286 states that Relying Parties may be exposed to inconsistent contents of the repository and need to mitigate this.  This is likely to be caused by the lack of atomicity during repository updates, both on the part of the published and, more likely, on the part of the RP.

> Repository operators MUST implement some form of repository update procedure that mitigates, _to the extent possible_, the risk that **RPs** that are performing retrieval operations on the repository **are exposed to inconsistent, transient, intermediate states** during updates to the repository publication point (directory) and the associated manifest.

**Comment by ksriram25** [comment]
I am OK now with leaving it as is the wording about consistency of RPKI.
